### ISSUE TITLE
The zip file under Downloads is broken.

### ISSUE THREAD

**Issue by finsterdexter** [Twitterizer/Twitterizer#1]
The archive is either corrupt or incomplete.

**Comment by dschinkel** [comment]
If you're gonna provide a framework, please keep it up to date and make your crap accessible if it's broken.

**Comment by finsterdexter** [comment]
You can still download the code. Just go to the top level of the repo and hit the little "ZIP" button and it will zip up the repo so you can download it. Maybe lay off the coffee a little bit.

**Comment by dschinkel** [comment]
Give me a break, just fix it.  People first go to the download section.  Like everyone knows your work around.  If you are providing a downloadable file, it needs to work.

**Comment by finsterdexter** [comment]
No, _I_ am the one who posted it. And your behavior is completely unprofessional. If I were the developers of this library, I'd be very disinclined to respond to your request at all.

**Comment by DigitallyBorn** [comment]
@espresso1000 Sorry I haven't been able to do for you what you have within your ability to do for yourself: build the source code. I've actually been pretty busy.

I've deleted the file so you don't waste your time downloading it again and again. Feel free to grab the source and build the library yourself. Here's a link to download a zip of the source code: https://github.com/Twitterizer/Twitterizer/zipball/master

Let me know if you have any open source projects of your own, I'll be happy to stop by and provide some assistance.

**Comment by dschinkel** [comment]
Thank you sir.  I may add though I have not used GitHub before so I would not have known the ability to zip it myself.  I was just going off your downloads which probably most newbies would have tried to do in the first place.
