### ISSUE TITLE
Incorrect filesize in UpdateProfileImageCommands

### ISSUE THREAD

**Issue by ecnepsnai** [Twitterizer/Twitterizer#10]
I noticed a mistake in UpdateProfileImageCommands in Twitterizer2.

Length returns the file size in bits.  Not bytes.  So by checking if the image is larger than 89600 bits, you actually limiting the users to files smaller than 88kb.

The correct integer is 716800.

**Comment by russau** [comment]
Here's the relevant line of code:
https://github.com/Twitterizer/Twitterizer/blob/6511fa9555527e66a5fb29998a8ed26a76a308a3/Twitterizer2/Methods/Account/UpdateProfileImageCommand.cs#L66
