### ISSUE TITLE
Getting Retweets

### ISSUE THREAD

**Issue by araratispiroglu** [Twitterizer/Twitterizer#13]
I tried to getting retweets of specific tweet. When I tried TwitterStatus.Retweets(token, tweet.TweetId) like this, it throws NullReferanceExaptation - (Object reference not set to an instance of an object) and site was crashed then I tried like TwitterStatus.Retweets(token, tweet.TweetId, new RetweetsOptions()) this and it worked.

**Comment by DigitallyBorn** [comment]
Are you using the latest source code, or the binary download?

**Comment by araratispiroglu** [comment]
Yeah, I used latest binary

**Comment by DigitallyBorn** [comment]
You might try to grab the source code. A number of issues have been addressed already.

**Comment by DigitallyBorn** [comment]
I'm going to close this, since there hasn't been any response. Feel free to re-open if you're still having this issue.
