### ISSUE TITLE
StreamOptions constructor needs to be public

### ISSUE THREAD

**Issue by finsterdexter** [Twitterizer/Twitterizer#2]
Right now, it's protected. This is obviously a problem, as I can't set the `StreamOptions` when instantiating `TwitterStream`... it requires passing in a `StreamOptions` instance... which I can't create because the constructor is protected...

What I ended up doing was creating my own `CustomStreamOptions` class that inherits from `StreamOptions` and then passing that into `TwitterStream`. Seems like a silly hoop to have to jump through.

**Comment by DigitallyBorn** [comment]
The `StreamOptions` class is a base class for individual stream types. For example, `UserStreamOptions`. So far, this is the only class that inherits `StreamOptions`, but there will be at least one other to support site streams, once they are implemented.

**Comment by finsterdexter** [comment]
I don't see a `PublicStreamOptions`, though which is what I'm using. I haven't gone through enough of the source to know if the `UserStreamOptions` would work when I'm calling `TwitterStream.StartPublicStream`. Is the intention to use `UserStreamOptions` with the non-user stream?

**Comment by DigitallyBorn** [comment]
As far as I know, public streams hasn't been added to the library yet, so the options class wouldn't exist.

**Comment by finsterdexter** [comment]
The method and callbacks are there. For example,
TwitterStream.StartPublicStream()

On Mon, Feb 20, 2012 at 1:06 PM, Ricky Smith <
reply@reply.github.com

**Comment by GoldenTao** [comment]
The stream object has a public property StreamOptions that you can change between stopping and restarting the public stream, which will change the tracks etc.

You are right, stream options was protected I believe in the older code, I'm just having a little trouble checking it in and you should then be right to create it yourself.
