### ISSUE TITLE
Twitter text being chopped off after adding RT @username 

### ISSUE THREAD

**Issue by justinlfang** [Twitterizer/Twitterizer#24]
One real example. The original tweet has 140 characters: 
"I am disappointed in today's #SCOTUS decision. The health care law is an overreach of the federal govt. This law must be repealed#fullrepeal"

The library appends RT @username to it, then the Text property of a TwitterStatus becomes:
"RT @GovernorBentley: I am disappointed in today's #SCOTUS decision. The health care law is an overreach of the federal govt. This law mu ..."

That is, "st be repealed#fullrepeal" was chopped off from the original tweet.

**Comment by DigitallyBorn** [comment]
The library doesn't add the RT command. This is a function of Twitter. Back in the day, retweets were issued by using the RT command, and it continues to function that way now, even when using the Retweet endpoint. Your code should validate for this scenario.

**Comment by justinlfang** [comment]
Hi @DigitallyBorn,

Could you please show me how to validate for this scenario? Anything else need to be check beyond the Text property of a TwitterStatus object in order to get all 140 characters? Thank you.
