### ISSUE TITLE
Streaming Library defines Location object properties as int instead double

### ISSUE THREAD

**Issue by damiancalvo** [Twitterizer/Twitterizer#31]
Streaming Library defines Location object properties as int instead double.
The API documentation says that it allows pass decimal values in Latitude and Longitude parameters when filter streaming by location.

**Comment by DigitallyBorn** [comment]
Sounds like a pretty easy fix. Would you submit a pull request?

**Comment by damiancalvo** [comment]
I've submitted a pull request.
