### ISSUE TITLE
Twitter Streaming API 1.1

### ISSUE THREAD

**Issue by genisbarrera** [Twitterizer/Twitterizer#33]
Do you know if Twitterizer Streaming API will be updated to Twitter Streaming API 1.1?

Thanks

**Comment by DigitallyBorn** [comment]
My plan is to fold streaming support into the core library since streaming has become an integral part of the twitter api.

**Comment by gitbrook** [comment]
Cool, if this is finished in 11 days then all should be fine. - Thanks

**Comment by hupseb** [comment]
Well 1.0 is depricated now. Is it planned to upgrade to v.1.1?

**Comment by hupseb** [comment]
If i have a look at the 1.1 document not much changed... I replace the URL with new one and try it :)

**Comment by davidebbo** [comment]
Any luck with new API? My Twitterizer code is now broken with _"The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview."_.

Is there a way to make this work with Twitterizer, or is my best bet to hunt for another library? Thanks!

**Comment by DigitallyBorn** [comment]
I know that the required changes have been made and I believe they are fairly straight forward, but no one has committed them, yet. I've added you to the developers group so you can commit to the repo.

**Comment by davidebbo** [comment]
Thanks! Well, if there is a good chance that someone has made the changes already, I'll just wait for that.

If someone gets it in, will you be able to get a NuGet package out? Or maybe add someone else as a co-owner on NuGet to do it?

**Comment by dsuraj** [comment]
Hello David,

You can try LinqtoTwitter library.
http://linqtotwitter.codeplex.com/

On Mon, Jun 24, 2013 at 9:13 AM, David Ebbo notifications@github.comwrote:

> Thanks! Well, if there is a good chance that someone has made the changes
> already, I'll just wait for that.
> 
> If someone gets it in, will you be able to get a NuGet package out? Or
> maybe add someone else as a co-owner on NuGet to do it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Twitterizer/Twitterizer/issues/33#issuecomment-19887809
> .

## 

Thanks & Regards,
Suraj Deshpande
+91-8149213233

**Comment by davidebbo** [comment]
Thanks, I was just asking on Twitter, and that seemed like the crowd favorite. Though I'm still hoping to use an updated Twitterizer so I don't have to change my code any more than necessary :)

**Comment by dsuraj** [comment]
Sounds good, let me know if I can help you from my side. Cheers!!

On Mon, Jun 24, 2013 at 10:26 AM, David Ebbo notifications@github.comwrote:

> Thanks, I was just asking on Twitter, and that seemed like the crowd
> favorite. Though I'm still hoping to use an updated Twitterizer so I don't
> have to change my code any more than necessary :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Twitterizer/Twitterizer/issues/33#issuecomment-19889105
> .

## 

Thanks & Regards,
Suraj Deshpande
+91-8149213233

**Comment by dmaidon** [comment]
There is an updated library on BitBucket.  Author is Japanese and cannot speak or write English.  I started using it and my program works the way it did with v1.

https://bitbucket.org/szrsharp/twitterizer-remaked-for-api-1.1

**Comment by davidebbo** [comment]
That worked, thanks! Strange that the repo is not actually a fork, but is a new repo, making it hard to contribute back here. Oh well, I'm unblocked for now :)

**Comment by meebey** [comment]
I haven't looked at the streaming API yet but the regular basic APIs should work with v1.1 now, see the develop branch.

**Comment by meebey** [comment]
I updated the Stream API endpoints to 1.1, see ab66927b803f8affd7dd03f6466bb8abe93d30d1
