### ISSUE TITLE
TwitterUser.IsFollowedBy always returns null

### ISSUE THREAD

**Issue by mikejhale** [Twitterizer/Twitterizer#40]
The IsFollowedBy field is returning null regardless of whether or not the authenticated user is following them.

**Comment by asmandria** [comment]
I can reproduce this issue

**Comment by DigitallyBorn** [comment]
According to the Twitter documentation (https://dev.twitter.com/docs/platform-objects/users), the followed_by field is no longer present in the user.

Also, note that many of the fields are perspectival and are not returned by every API endpoint (hence it being nullable).

I've created #64 to track the removal of depreciated fields from the user.
