### ISSUE TITLE
Twitter API v1.1

### ISSUE THREAD

**Issue by jonscottsheldon** [Twitterizer/Twitterizer#46]
When is it anticipated that Twitterizer will support the Twitter v1.1 API?

I've tried changing the "APIBaseAddress" to "http://api.twitter.com/1.1/" and any api calls fail with a 401 Unauthorized exception.

**Comment by DigitallyBorn** [comment]
I am currently working on making the needed changes to upgrade the library to 1.1. I don't have a time frame for completing the changes as of yet. Until my OAuth code is upgraded the library will not work with any of the new endpoints.

**Comment by defly** [comment]
Hi. When can we expect support the Twitter Api v1.1?
v1.0 will be deprecated after 5 March.

**Comment by junsp** [comment]
Hey, using your Twitterizer 2, with end points changed, I see many of them working fine..
Did you somehow upgrade your OAuth library?

I am using Twitterizer version before Nov. 7, 2012.. I still see 1.1 endpoints working..  am I missing something ?

I mean, I changed to new Resource URLs in your source code, also changing some of the structures getting rid of deprecated properties..working fine for most of the calls, except such as publictimeline, which you have to use instead GET statuses/sample,  with URL https://stream.twitter.com/1/statuses/sample.json ..
