### ISSUE TITLE
Unable to Parse Json

### ISSUE THREAD

**Issue by matt-lethargic** [Twitterizer/Twitterizer#47]
I'm running a .Net 4 website, I've installed twitterizer from nuget
"install-package twitterizer"
which has installed version 2.4.2 and Newtonsoft.Json v4.5.5

When I run the code:
UserTimelineOptions options = new UserTimelineOptions();
options.ScreenName = twitterId;
options.Count = _tweetCount;

var timeline = TwitterTimeline.UserTimeline(options);

timeline.Result = Unknown
and ErrorMessage = "Unable to parse JSON"

**Comment by DigitallyBorn** [comment]
This is a duplicate issue. Please refer to issue #36.
