### ISSUE TITLE
Get tailored trends

### ISSUE THREAD

**Issue by RhysTowey** [Twitterizer/Twitterizer#48]
Is it possible to get the users specific Tailored Trends? I am currently using the following code to get worldwide trends:

  TwitterResponse<TwitterTrendCollection> tr = TwitterTrend.Trends(1); 
            foreach (TwitterTrend tnds in tr.ResponseObject)
            {
                Label trend = new Label();
                trend.Content = tnds.Name;
                trend.Foreground = Brushes.White;
                trend.Margin = new Thickness(10, 0, 0, 0);
                TrendsBar.Children.Add(trend);
            }

**Comment by DigitallyBorn** [comment]
I cannot find any place in the Twitter API documentation that speaks of personalized trends.

**Comment by RhysTowey** [comment]
Oh well, never mind. Thanks Ricky.
