### ISSUE TITLE
Unknown error 9 when using twitterizer2.dll

### ISSUE THREAD

**Issue by arthandy** [Twitterizer/Twitterizer#60]
Since the 14th of this month my embedded code using twitterizer2.dll have been failing with an error code of 9. Do you have a recompiled version of the dll that includes the "https://" connection issues, and if so where can I download the new version? Thanks so much.

**Comment by jamiehowarth0** [comment]
A new release on Nuget is in the works and I hope to have this ready for GA both here and on Nuget in the next two weeks.

**Comment by arthandy** [comment]
OK, thanks Ben. Is there a way you can let me know as soon as it is ready, and the proper instructions for installing it?

**Comment by meebey** [comment]
I fixed this already in the develop branch see f6f1e5bb606986771dcd9841385d16aaf401cd83
