### ISSUE TITLE
Twitterizer Library working fine at local but not on server

### ISSUE THREAD

**Issue by manjinder018** [Twitterizer/Twitterizer#62]
Twitterizer Library working fine at local system but not on server after deploy, every time return "unauthorize" status when call update() . Any Idea ?

**Comment by meebey** [comment]
Provide a full stack trace. It sounds a bit like the oauth token is missing or no longer valid.

**Comment by manjinder018** [comment]
I am using Twitterizer dll, It working fine (Local/Test server/Product server) when redirect to twitter for login and after authentication redirect back to my application, then I store that token in session, when i Reply,Retweet,Favoirt any tweet, Its works for me at local but does not work on test server and production server, Every time get same error message "The remote server returned an error: (401) Unauthorized". Any Idea ? Thanks in advance.

**Comment by jamiehowarth0** [comment]
@manjinder018 for us to diagnose this, we need a stack trace. Can you go into your Event Viewer on your server/s and find in either the "Application" or "System" views where ASP.NET is reporting an Error or Warning? The stack trace will be in there.

**Comment by manjinder018** [comment]
Thanks all, I checked on server Twitterizer Library was old version. I updated latest one and its working fine for now. Thanks for your help friends
