### ISSUE TITLE
Twitterizer not working when a tweet contains an image/pic

### ISSUE THREAD

**Issue by DigitallyBorn** [Twitterizer/Twitterizer#7]
This was sent in by Paul Stoker via email:

> I have noticed a problem with Twitterizer in that it's has been working fine until my client added a tweet to her account containing an image powered by Photobucket.
> Then we started getting the Object reference error above. It's taken a an hour or two to determine that it was actually the tweet causing the issue which I've now removed however how can I get round this problem?
> My code is below which is a very basic solution for pulling the time line in:

```
OAuthTokens tokens = new OAuthTokens();
tokens.AccessToken = AccessToken;
tokens.AccessTokenSecret = AccessTokenSecret;
tokens.ConsumerKey = ConsumerKey;
tokens.ConsumerSecret = ConsumerSecret;

try
{
  UserTimelineOptions opts = new UserTimelineOptions();
  opts.IncludeRetweets = false;
  opts.UseSSL = true;
  opts.Count = 5;

  TwitterResponse<TwitterStatusCollection> timeLine =  TwitterTimeline.UserTimeline(tokens, opts);
  uxTweets.DataSource = timeLine.ResponseObject;
  uxTweets.DataBind();
}
catch
{
  uxError.Text = "<p class=\"p1\">Twitter isn't configured correctly. Twitter is not responding.</p>";
}
```

**Comment by creative3k** [comment]
is it fixed or not ?? still getting errors when the tweet consist of image

**Comment by DigitallyBorn** [comment]
It doesn't look like any developers have taken up the cause and I have not had the time. You're welcome to be the developer that charges ahead with this.

**Comment by creative3k** [comment]
To be honest I have no idea how to fix it coz of lack of developing exposure, but i would love to troubleshoot it and find the actual coz of error, can you assist me where to start , do i have to look into the Twitterizer api methods.

**Comment by DigitallyBorn** [comment]
Download the source, add the twitterizer project to your solution, then change your project's reference to use the twitterizer code and not the pre-built assembly. From then on, it's just like any other code: put a breakpoint and step through the code.

**Comment by creative3k** [comment]
I checked with the latest version of api , its working fine , below is my code:

``` csharp
 using System;
 using System.Collections.Generic;
 using System.Linq;
 using System.Web;
 using System.Web.UI;
 using System.Web.UI.WebControls;
 using Twitterizer;

public partial class usercontrols_tweets : System.Web.UI.UserControl
{
protected void Page_Load(object sender, EventArgs e)
{
    if (!Page.IsPostBack)
    {
        try
        {

            UserTimelineOptions options = new UserTimelineOptions();
            options.ScreenName = "twitterScreenName";
            TwitterStatusCollection mytweets = TwitterTimeline.UserTimeline(options).ResponseObject;

            int counter = 0;
            string TwitterWrapper = "";
            foreach (TwitterStatus myStatus in mytweets)
            {
                TwitterWrapper += "<li"><p><a href=\"http://twitter.com/" + myStatus.User.ScreenName + "\" target=\"_blank\">" + Server.HtmlEncode(myStatus.Text) + "</a></p></li>";
            }

            ltlmyTweets.Text = TwitterWrapper;


        }
        catch (Exception ex)
        {

        }

    }
}
}
```

**Comment by creative3k** [comment]
during debug 
TwitterStatusCollection mytweets = TwitterTimeline.UserTimeline(options); was throwing object reference error , adding ResponseObject sorts out the issue

**Comment by DigitallyBorn** [comment]
Are you suggesting that this isn't an error inside of Twitterizer?

**Comment by creative3k** [comment]
Yep coz its working now with the latest api , adding response object
