### ISSUE TITLE
callback url for  wpf application

### ISSUE THREAD

**Issue by aravind1234** [Twitterizer/Twitterizer#77]
Hi,
        After entering the  username and password  when  i clicked the sign in button it's not redirecting to the specified callback url,it's stays on the same page.As it is a wpf application i don't know how to set the callback url.
Any suggestions...

**Comment by DigitallyBorn** [comment]
Can you give a little code to show how you are setting up the OAuth flow? You should be setting the callback when you invoke [`GetRequestToken`](https://github.com/Twitterizer/Twitterizer/blob/58d26dc57eb14b091b331fa4365e5037c91959dd/Twitterizer2/OAuth/OAuthUtility.cs#L58).

**Comment by DigitallyBorn** [comment]
For desktop apps, the recommended flow is not to use a callback url, but to use PIN-based authentication. After the user grants your application access, they are presented with a PIN with instructions to return to your application. Your app should collect that PIN from the user, then submit that in the final OAuth request (the result of which is the access token).

**Comment by DigitallyBorn** [comment]
@brendan10211 You're exactly wrong: applications should _always_ supply a callback url in the request. In fact, in your screenshot it says that: 

> OAuth 1.0a applications should explicitly specify their oauth_callback URL on the request token step, regardless of the value given here.

You are correct, however, that for PIN-based authentication, `oob` should be supplied as the callback url.

**Comment by 7596ff** [comment]
I'm dumb, sorry :p

**Comment by DigitallyBorn** [comment]
Not dumb, I only wanted to be absolutely clear for anyone reading this.
