### ISSUE TITLE
SSL3 POODLE

### ISSUE THREAD

**Issue by qpmelkor** [Twitterizer/Twitterizer#78]
Hi, thank you for your work, lib is great!

But i have problem with your library after disabling SSL3 on twitter (https://twitter.com/twittersecurity/status/522190947782643712), getting error:

"The request was aborted: Could not create SSL/TLS secure channel."

Is there a way to force your lib use TLS instead SSL3?

**Comment by alharbin** [comment]
Hi,
Yes of course!
1-Open the Twitterizer project.
2-Go to "WebRequestBuilder" class .
3-At line 247 and change Ssl3 to Tls
                ServicePointManager.SecurityProtocol =
SecurityProtocolType.Tls;// .Ssl3;

Enjoy :)

On Fri, Oct 17, 2014 at 8:36 AM, qpmelkor notifications@github.com wrote:

> Hi, thank you for your work, lib is great!
> 
> But i have problem with your library after disabling SSL3 on twitter (
> https://twitter.com/twittersecurity/status/522190947782643712), getting
> error:
> 
> "The request was aborted: Could not create SSL/TLS secure channel."
> 
> Is there a way to force your lib use TLS instead SSL3?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Twitterizer/Twitterizer/issues/78.

## 

Please visit one of these websites :
http://www.islamway.net/mohammad/
http://english.islamway.com/

**Comment by meebey** [comment]
On Mono it is still working without modifying the source

**Comment by meebey** [comment]
Ewww, Twitterizer modifies ServicePointManager which applies to the complete AppDomain.... I guess Mono is not relying on ServicePointManager and thus it still works despite setting it to SSL3

**Comment by meebey** [comment]
Can someone test on .NET what happens if you remove both ServicePointManager lines?

```
            ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3;
```

Does it still work?

**Comment by meebey** [comment]
Errr in the develop branch that SecurityProtocol line does not exist. Are you using Twitterizer from the wrong branch? master is completely unsupported.

**Comment by meebey** [comment]
Ok this is a regression from e6adfc3911b4c0ff47c01f8ab6ba13b9f757f776 which should never have been merged. I will revert that commit now and all should be good again.

**Comment by meebey** [comment]
Fixed in 923feb1a6d667066f984411b3e71ef2eb1066580

**Comment by qpmelkor** [comment]
Thanks a lot for your help, issue is solved for me.

**Comment by Alchemy86** [comment]
Can you confirm this is working?
I have download the project and converting to visual studio 2013 results in compile errors and downloading the Dll from the examples also fails to send a message since this error can up.

Can someone please post a link to a built DLL that has this fix so I can confirm this is working for me.

**Comment by qpmelkor** [comment]
I built it in VS 2012 and it works...
Do you still need compiled dll?
