### ISSUE TITLE
Introduce a common Interface for tweetable objects

### ISSUE THREAD

**Issue by mabster** [Twitterizer/Twitterizer#8]
A feature from (the now defunct) TweetSharp that I'd love to see in Twitterizer:

Statuses, search results and direct messages all share some common properties. User, text, timestamp etc. It would be nice if they all implemented a common "ITweetable" (or something more in line with the Twitterizer naming conventions) so that we could define methods that can work with all three kinds of updates.

Once ITweetable existed, The corresponding collection classes like TwitterStatusCollection could implement `IEnumerable<ITweetable>` so that, again, methods could accept any kind of collection of updates as a parameter.

**Comment by DigitallyBorn** [comment]
Aha. I understand. That would make it nice and easy to write a blended list of results from various sources .. and I don't think it would be very difficult to do.

**Comment by mabster** [comment]
Feel free to check out the source code for Halfwit to get a feel for how I'm using this feature with TweetSharp. https://bitbucket.org/mabster/halfwit

**Comment by DigitallyBorn** [comment]
This is being written into the new Twitterizer3 library.
