### ISSUE TITLE
Parsing AccessLevel from Headers [Core/TwitterCommand.cs->ParseAccessLevel)

### ISSUE THREAD

**Issue by silviabastos** [Twitterizer/Twitterizer#91]
Hi!
I have found a bug in method ParseAccessLevel (Core/TwitterCommand.cs).
When you check if response Headers contains "X-Access-Level" the comparison isn't case insensitive and real Twitter header is "X-access-level", so Twitterizer also returns AccessLevel.Unavailable.
Solution is like  PareRateLimitHeaders method does, a case insesitive comparison:

 if (responseHeaders.AllKeys.Any(x => x.Equals("X-Access-Level", StringComparison.InvariantCultureIgnoreCase)))

Silvia.

**Comment by meebey** [comment]
Fixed, thank you for the report!
