### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by stanislavromanov** [Twitterizer/Twitterizer#96]
Is it possible to make this library work on .NET Core 1.0+?

**Comment by kylegalbraith** [comment]
I too would have this use case, is there any plan or details on how to make this work?

**Comment by meebey** [comment]
Try it and see what needs to be done? (say missing types, assembly references etc)
I have no .NET Core setup yet to test this myself.

**Comment by SeanFarrow** [comment]
Having had a quick look, it seems like it will be references in the main that will need changing. Whilst we're at it should we not upgrade all other packages?
I'm happy to help with this where I can or review pr's. What frameworks are we supporting?
